// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD65sj0lyF0fsrgsWUJFKK61ekedzG9IRg',
    appId: '1:344130744435:web:2a0cd43bdf4509812c3a06',
    messagingSenderId: '344130744435',
    projectId: 'needtoassistvendor',
    authDomain: 'needtoassistvendor.firebaseapp.com',
    storageBucket: 'needtoassistvendor.firebasestorage.app',
    measurementId: 'G-ZGLXRZQZMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcBM3R0J1yHNaw-iRcPpZANm7KQussr1E',
    appId: '1:344130744435:android:d1c0f2b8b9df61a12c3a06',
    messagingSenderId: '344130744435',
    projectId: 'needtoassistvendor',
    storageBucket: 'needtoassistvendor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmzce1Bb_5TmZi_3gJJYLDJ5lcO5kysfs',
    appId: '1:344130744435:ios:32da7578a4209a342c3a06',
    messagingSenderId: '344130744435',
    projectId: 'needtoassistvendor',
    storageBucket: 'needtoassistvendor.firebasestorage.app',
    iosBundleId: 'com.DSWale.dsService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmzce1Bb_5TmZi_3gJJYLDJ5lcO5kysfs',
    appId: '1:344130744435:ios:32da7578a4209a342c3a06',
    messagingSenderId: '344130744435',
    projectId: 'needtoassistvendor',
    storageBucket: 'needtoassistvendor.firebasestorage.app',
    iosBundleId: 'com.DSWale.dsService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD65sj0lyF0fsrgsWUJFKK61ekedzG9IRg',
    appId: '1:344130744435:web:e6af4df76478a9b82c3a06',
    messagingSenderId: '344130744435',
    projectId: 'needtoassistvendor',
    authDomain: 'needtoassistvendor.firebaseapp.com',
    storageBucket: 'needtoassistvendor.firebasestorage.app',
    measurementId: 'G-1RWNVYYMGP',
  );
}
